### PR TITLE
Generic derive for user types

### PR DESCRIPTION
**Pull request by dam5h**
As discussed last week, I played around some more with the derive macro to get it to use a field called `input` on the target "Candle" struct.  Interestingly I had to split out `CandleComponent` into 2 traits, one that is generic and one that is not.  The compiler didn't like having the whole `CandleComponent` trait being generic as it could only infer the generic type for the `update` method, since that is the only one that required a generic parameter, I split them out. 

I have added an example called `user_trade_type` to show how someone could use a type other than `Trade` for the input into the aggregators.

This could probably be cleaned up some, but wanted to get it out there to see what you thought before doing much more.

Cheers!
Dave

### CODE REVIEW

**Comment by dam5h** [comment]
Howdy @MathisWellmann, how's it going?  Wondering if you had a chance to take a look at this PR or not.  No rush, just didn't know if you saw it post.  Cheers!

**Comment by MathisWellmann** [comment]
Hi Dave, I saw it am I'm exited to take a deeper look when the weekend comes as I'm quite busy with work during the week. So stay tuned!

**Comment by MathisWellmann** [comment]
Hi Dave,
This looks really good. I'll merge and publish these changes today.
Thanks for these great contributions :D

**Comment by dam5h** [comment]
Thanks @MathisWellmann, looking forward to using the library a little more when I get some time again for some personal projects.  Cheers!

**Pull request merged**
